version: "3"
services:
  web:
    container_name: campr-injection-workshop
    image: openjdk:8-jdk-slim
    command: bash -c "cd /app && ./gradlew -g /app/.gradle bootRun -x test"
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db_server
    hostname: db_server
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'injection'

